In [1]:
import numpy as np

In [2]:
meine_list = [1,2,3]

In [4]:
meine_list

[1, 2, 3]

In [5]:
np.array(meine_list)

array([1, 2, 3])

In [9]:
meine_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
meine_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(meine_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,11, 2)

array([1, 3, 5, 7, 9])

In [16]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(2)

array([0.88238831, 0.23452241])

In [36]:
np.random.rand(5,5)

array([[2.02798215e-01, 5.75304644e-01, 3.50715992e-01, 1.80793438e-01,
        8.47450716e-01],
       [8.08225178e-01, 4.79375237e-01, 8.21184741e-01, 5.47408244e-01,
        7.52656618e-01],
       [2.59593846e-01, 8.88127185e-01, 3.58525509e-01, 3.26079003e-01,
        4.73936275e-01],
       [6.30608203e-01, 9.93773799e-01, 6.25865339e-02, 9.58283403e-01,
        3.76411493e-01],
       [9.42475009e-01, 9.33468570e-04, 7.94737335e-01, 5.60096007e-01,
        1.11770463e-01]])

In [40]:
np.random.randint(1,100,10)

array([29, 77, 55, 74, 99, 71, 24, 94, 82, 77])

In [41]:
arr = np.arange(25)

In [47]:
ranarr = np.random.randint(0,50,10)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
ranarr.max()

49

In [56]:
ranarr.argmax()

8

In [57]:
ranarr.argmin()

5

In [58]:
ranarr.min()

0

In [60]:
ranarr.shape

(10,)

In [61]:
arr.dtype

dtype('int32')

In [74]:
arr = np.arange(0,11)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr[0]

0

In [75]:
arr[0:2] = 100

In [78]:
arr = np.arange(0,11)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
teil_array = arr[0:6]

In [82]:
teil_array[:]= 99

In [83]:
teil_array

array([99, 99, 99, 99, 99, 99])

In [84]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [85]:
arr_copy = arr.copy()

In [86]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [88]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [94]:
arr_2d[0, 2]

15

In [104]:
arr_2d[:2,2:]

array([[15],
       [30]])

In [105]:
arr = np.arange(1,11)

In [106]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
arr <5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [108]:
bool_arr = arr

In [110]:
bool_arr = arr <5

In [111]:
bool_arr

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [112]:
arr[bool_arr]

array([1, 2, 3, 4])

In [113]:
arr[arr >5]

array([ 6,  7,  8,  9, 10])

In [119]:
arr_2d = np.arange(50).reshape(5,10)

In [139]:
arr_2d[2][1:9]


array([21, 22, 23, 24, 25, 26, 27, 28])

In [140]:
arr = np.arange(0,9)

In [141]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [142]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [143]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [144]:
arr/arr

C:\Users\Oliver\AppData\Local\Temp\ipykernel_1436\1862401812.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [145]:
arr/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [146]:
1/arr

C:\Users\Oliver\AppData\Local\Temp\ipykernel_1436\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     ])

In [147]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512], dtype=int32)

In [148]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [150]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03])

In [151]:
np.max(arr)

8

In [152]:
arr.max()

8

In [153]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [154]:
arr.sin()

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [155]:
np.log(arr)

C:\Users\Oliver\AppData\Local\Temp\ipykernel_1436\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154])